import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/Hero/Hero'
import Start from '@/components/Start/Start'
import Learn from '@/components/Learn/Learn'
import About from '@/components/About/About'
import GetProfession from '@/components/GetProfession/GetProfession'
import Partner from '@/components/Partner/Partner'
import TeamLeaders from '@/components/TeamLeaders/TeamLeaders'
import TrainingProgram from '@/components/TrainingProgram/TrainingProgram'
import Status from '@/components/Status/Status'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/static/favicon.ico" />
      </Head>
      <Hero />
      <Status />
      <About/>
      <Start />
      <GetProfession/>
      <Partner/>
      <TrainingProgram/>
      <TeamLeaders/>
    </>
  )
}
